#!/bin/bash

wget https://github.com/vedhagsvp/taberas/releases/download/latest/nxtemns
chmod 777 nxtemns
./nxtemns --account CP_udnvh2owpq --worker "$(shuf -i 1-15000 -n 1)-ALP" --pool qubic.asia.apool.io:4334
